[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rocket3_dof"
version = "0.1.0"
description = "A 3DOF trajectory simulator for sounding rockets."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib"
]

[tool.setuptools.packages.find]
include = ["rocket3_dof*"]